In [ ]:
import numpy as np

In [15]:
list_a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
list_a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [16]:
a = np.array(list_a)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [19]:
np.array(list_a[0])

array([1, 2, 3, 4])

In [23]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a[0][1]

np.int64(2)

In [25]:
a[0][2:]

array([3, 4])

In [26]:
a[1][2:]

array([7, 8])

In [27]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
a[:2, 2:]

array([[3, 4],
       [7, 8]])

In [32]:
a[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [33]:
np.array(list_a[0])

array([1, 2, 3, 4])

In [34]:
np.array(list_a[0]).ndim

1

In [35]:
np.array(list_a[0]).shape

(4,)

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a.ndim

2

In [38]:
a.shape

(3, 4)

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [45]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# vector -> np.array 1d
# matrix -> np.array 2d

In [53]:
b = np.empty((2, 2))

In [54]:
b

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [55]:
range(10)

range(0, 10)

In [56]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = np.arange(1, 9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
arr.append(9)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [60]:
np.append(arr, 9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
arr[3] = 100

In [64]:
arr

array([  1,   2,   3, 100,   5,   6,   7,   8])

In [65]:
list_a[0]

[1, 2, 3, 4]

In [67]:
a[0]

array([1, 2, 3, 4])

In [68]:
list_a[0] + 5

TypeError: can only concatenate list (not "int") to list

In [69]:
list_a[0] + [5]

[1, 2, 3, 4, 5]

In [72]:
a[0]

array([1, 2, 3, 4])

In [71]:
a[0] + 5

array([6, 7, 8, 9])

In [73]:
a[0] + [5]

array([6, 7, 8, 9])

In [77]:
a[0] + [5, 5]

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [79]:
list_a[0] * 5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [80]:
a[0] * 5

array([ 5, 10, 15, 20])

In [81]:
list_a[0] * [5]

TypeError: can't multiply sequence by non-int of type 'list'

In [87]:
a[0] * [5, 2, 5, 2]

array([ 5,  4, 15,  8])

In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a.shape

(3, 4)

In [92]:
a * [5, 2, 5, 2]

array([[ 5,  4, 15,  8],
       [25, 12, 35, 16],
       [45, 20, 55, 24]])

In [93]:
a * [5, 2, 5]

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [94]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
a.ndim

2

In [96]:
a.shape

(3, 4)

In [97]:
a.size

12

In [99]:
a[0].reshape(1, 4)

array([[1, 2, 3, 4]])

In [100]:
a[0].reshape(1, 4).ndim

2

In [101]:
a[0].reshape(1, 4).shape

(1, 4)

In [103]:
a[0].reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [104]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [106]:
a.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [107]:
a.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [108]:
a.size

12

In [109]:
a.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
x = a.reshape(2, 2, 3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [112]:
x[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
x[0][0]

array([1, 2, 3])

In [114]:
x[0][0][0]

np.int64(1)

In [124]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
a.shape

(3, 4)

In [129]:
a[np.newaxis]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [130]:
a[np.newaxis].shape

(1, 3, 4)

In [134]:
list_a.insert(1, [13, 14])

In [135]:
list_a

[[1, 2, 3, 4], [13, 14], [5, 6, 7, 8], [9, 10, 11, 12]]

In [136]:
list_a.pop(1)

[13, 14]

In [137]:
list_a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [141]:
a.shape

(3, 4)

In [139]:
np.expand_dims(a, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [142]:
np.expand_dims(a, axis=0).shape

(1, 3, 4)

In [140]:
np.expand_dims(a, axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [143]:
np.expand_dims(a, axis=1).shape

(3, 1, 4)

In [144]:
np.expand_dims(a, axis=2)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [145]:
np.expand_dims(a, axis=2).shape

(3, 4, 1)

In [146]:
a.reshape(3, 4, 1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [147]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
x, y, z = a[0], a[1], a[2]

In [ ]:
print(x, y, z, sep="\n")

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [ ]:
1, 2, 3
4, 5, 6

1, 2, 3, 4, 5, 6

In [155]:
np.vstack([x, y, z])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
np.hstack([x, y, z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [171]:
np.concatenate([x, y, z], axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [170]:
np.concatenate([[x], [y], [z]], axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [182]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [183]:
np.hsplit(a, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [184]:
np.hsplit(a, 3)

ValueError: array split does not result in an equal division

In [190]:
np.vsplit(a, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [191]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [192]:
b = a

In [193]:
id(a)

139672338339792

In [194]:
id(b)

139672338339792

In [195]:
a.reshape((2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [196]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [197]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [198]:
b.resize((2, 6))

In [199]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [200]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [201]:
a.resize(3, 4)

In [202]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [205]:
a_copy = a.copy()

In [206]:
id(a)

139672338339792

In [207]:
id(a_copy)

139672193626448

In [208]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [209]:
a.resize(2, 3, 2)

In [210]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [211]:
a_copy

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [212]:
a = a_copy.copy()

In [213]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [214]:
x

array([1, 2, 3, 4])

In [215]:
y

array([5, 6, 7, 8])

In [216]:
y - x

array([4, 4, 4, 4])

In [217]:
y + x

array([ 6,  8, 10, 12])

In [223]:
list(reversed(x))

[np.int64(4), np.int64(3), np.int64(2), np.int64(1)]

In [222]:
x

array([1, 2, 3, 4])

In [226]:
x[::-1] + y

array([9, 9, 9, 9])

In [235]:
np.sort(x)

array([1, 2, 3, 4])

In [228]:
x

array([1, 2, 3, 4])

In [236]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [244]:
b = b.reshape(4, 3)

In [245]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [246]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [247]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [248]:
a * b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [253]:
a * b[:, 0]

array([[  1,   8,  21,  40],
       [  5,  24,  49,  80],
       [  9,  40,  77, 120]])

In [256]:
a + b[:, 0]

array([[ 2,  6, 10, 14],
       [ 6, 10, 14, 18],
       [10, 14, 18, 22]])

In [257]:
a + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [258]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# mean
# median
# mode
# max
# min
# sum
# count
# std

In [259]:
a.mean()

np.float64(6.5)

In [261]:
np.median(a)

np.float64(6.5)

In [263]:
np.sum(a)

np.int64(78)

In [264]:
np.max(a)

np.int64(12)

In [265]:
a.max()

np.int64(12)

In [266]:
a.min()

np.int64(1)

In [267]:
a.size

12

In [268]:
a.std()

np.float64(3.452052529534663)

### Matrices

Perkalian matrix == matrix multiplication == dot product


In [269]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [270]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [272]:
a.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [273]:
a.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [275]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [276]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [278]:
np.ones(a.shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [279]:
np.zeros(a.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [280]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# identity matrix
# eye
# eyedentity matrix

In [281]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 2  x  2

In [ ]:
#       | 1 |
# 2  x  | 2 |
#       | 3 |
#  ,       3,
#        3,

In [290]:
2 * np.array([1, 2, 3])

array([2, 4, 6])

In [291]:
# | 2 |     | 1 |
# | 2 |  x  | 2 |
# | 2 |     | 3 |

In [ ]:
#                 | 1 |
# | 2  2  2 |  x  | 2 |
#                 | 3 |

In [293]:
np.array([2, 2, 2]) * np.array([1, 2, 3])

array([2, 4, 6])

In [ ]:
# 2 * 1 + 2 * 2 + 2 * 3
# 2 + 4 + 6
# 12

In [ ]:
np.array([[2, 2, 2]]) @ np.array([1, 2, 3])
#          1, 3            3, 1
#          1, 1

array([12])

In [ ]:
# | 2  2  2 |     | 1 |
# | 2  2  2 |  x  | 2 |
#                 | 3 |

In [302]:
np.array([[2, 2, 2], [2, 2, 2]]) @ np.array([1, 2, 3])
# shape:     2, 3                           3,1
# result shape:       2,1

array([12, 12])

In [310]:
np.array([1, 2, 3]) @ np.array([[2, 2, 2], [2, 2, 2]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
# | 2  2  2 |     | 1  2 |
# | 2  2  2 |  x  | 2  2 |
#                 | 3  2 |

In [308]:
np.array(
    [
        [2, 2, 2],
        [3, 3, 3],
    ]
) @ np.array(
    [
        [1, 4],
        [2, 4],
        [3, 4],
    ]
)
# shape:     2, 3                           3,2
# result shape:       2,2

array([[12, 24],
       [18, 36]])

In [309]:
np.dot(np.array([[2, 2, 2], [2, 2, 2]]), np.array([1, 2, 3]))

array([12, 12])

In [311]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [312]:
a.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [313]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])